version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.3.0
  kube-orb: circleci/kubernetes@0.11.0

jobs:
  deploy:
    docker:
      - image: alpine:latest
    steps:
      - run:
          name: 'install curl'
          command: apk add curl
      - kube-orb/install-kubectl
      - run:
          name: "KUBE_CERTIFICATE_AUTHORITY to disk"
          command: echo -n "$KUBE_CERTIFICATE_AUTHORITY" | base64 -d > /root/.kube_certificate_authority
      - run:
          name: "kubectl configure cluster"
          command: kubectl config set-cluster "$KUBE_CLUSTER" --certificate-authority="/root/.kube_certificate_authority" --server="$KUBE_SERVER"
      - run:
          name: 'kubectl configure credentials'
          command: kubectl config set-credentials "circleci" --token="${KUBE_TOKEN}"
      - run:
          name: 'kubectl configure context'
          command: kubectl config set-context "circleci" --cluster="$KUBE_CLUSTER" --user="circleci" --namespace="formbuilder-submit-product-production"
      - run:
          name: 'kubectl use circleci context'
          command: kubectl config use-context "circleci"
      - checkout
      - run:
          name: 'kubectl apply'
          command: "kubectl apply --filename deploy/ --namespace formbuilder-submit-product-production"
      - run:
          name: 'rollout deployment'
          command: "kubectl rollout restart deployments -n formbuilder-submit-product-production"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          name: build_and_push
          account-url: AWS_ECR_ACCOUNT_URL
          region: AWS_DEFAULT_REGION
          repo: "formbuilder/fb-submit-product"
          tag: "${CIRCLE_SHA1},latest"
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - build_and_push
          filters:
            branches:
              only:
                - master
